# Generated by Django 5.0.4 on 2024-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPorProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.PositiveIntegerField()),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materias_primas.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materias_primas.materiaporproveedor')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias_primas.ordenmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='materiaporproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materias_primas.proveedor'),
        ),
    ]
